### ISSUE TITLE
Request help: confused in the code snippet of Adapter.lua

### ISSUE THREAD

**Issue by starsz** [casbin/lua-casbin#136]
Hello,
When I use the `authz-casbin` plugin in [Apache APISIX ](https://apisix.apache.org/docs/apisix/plugins/authz-casbin/) with a large policy, I found that the method of `newEnforcerFromText` takes a long time (about 40s).

After digging into it, the code below confused me:

https://github.com/casbin/lua-casbin/blob/249ae23a23d1be74762c7f3e25e5685e61b6e2d6/src/persist/Adapter.lua#L42-L56

1. Do we need to traverse `model.model[sec][key].policy` again of line~53.
2. Is there any way to improve this function?

**Comment by rushitote** [comment]
Hey,
Thanks for sharing this. I think you are right, the first traversal seems to be redundant and the performance can also be improved since we *probably* don't need to traverse the whole policy at every line load. I will try to fix this in a couple of days.

**Comment by rushitote** [comment]
Hey @starsz, could you please update Casbin to the latest version in your APISIX config and try again with the large policy?

**Comment by starsz** [comment]
> Hey @starsz, could you please update Casbin to the latest version in your APISIX config and try again with the large policy?

That's amazing ! I test it in my local environment and take a good effect. Thank you very much.
