### ISSUE TITLE
The installation module is missing the most critical casbin.lua In Ubuntu 20.04

### ISSUE THREAD

**Issue by conghuhu** [casbin/lua-casbin#139]
## Description
When I test the installation of lua-casbin, this situation occasionally occurs: the most critical casbin.lua is less than one of the dependencies installed.

### Env:
- OS: Ubuntu 20.04
- lua: 5.1 5.2 5.3 5.4
- luarocks: v3.3.1

### Normal installation：
![image](https://user-images.githubusercontent.com/56248584/185273882-4fded3d5-617a-495a-bba0-5584f2aac595.png)
### Missing installation
![image](https://user-images.githubusercontent.com/56248584/185274604-aa9148cc-9b92-4f49-a550-28e030ab2984.png)
![image](https://user-images.githubusercontent.com/56248584/185274635-36e49dab-b881-4eb3-bef4-07515d156afa.png)

As you can see from the picture, casbin.lua was not successfully installed locally, and the lack of it caused my reference to not find the casbin module

### Proposal
![image](https://user-images.githubusercontent.com/56248584/185274424-9b9c1d60-9091-4476-8d24-890f0339214c.png)
Is it possible to change `["casbin"] = "src/main/Enforcer.lua"` to `["casbin"] = "casbin.lua"`? Display the specified casbin.lua file.

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
I tried installing it by these two commands and it works well:
```sh
sudo luarocks install casbin
sudo luarocks show casbin
```

![image](https://user-images.githubusercontent.com/31135699/185338490-59cd630d-f12c-422d-b97c-4bbce7732292.png)

**Comment by conghuhu** [comment]
@rushitote 
I found this problem in github actions where the installation fails occasionally.
You need to try more times in CI, and this problem should be repeated.

**Comment by rushitote** [comment]
@conghuhu Could you please link which CI is failing randomly?

**Comment by conghuhu** [comment]
> @conghuhu Could you please link which CI is failing randomly?

I found it when I was developing luasql adapter
[CI link](https://github.com/conghuhu/lusql-CI/runs/7881837731?check_suite_focus=true)

**Comment by rushitote** [comment]
@conghuhu seems to be private 😅

**Comment by conghuhu** [comment]
> @conghuhu seems to be private 😅

Sorry，you can try again.

**Comment by rushitote** [comment]
Hmm, seems to happen when building the `.rock` file. Not sure, but I think this is a problem with LuaRocks than us if this happens randomly.

**Comment by conghuhu** [comment]
> 

OK, then I will run CI more times until it passes

**Comment by rushitote** [comment]
@conghuhu Does it fail randomly even when installing by `luarocks install casbin` (installing latest version)?

**Comment by conghuhu** [comment]
@rushitote Yes, I have tried build, install, and make, but the casbin.lua file is randomly missing and not installed
