### ISSUE TITLE
CI error: error semantic-release@20.0.2: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.18.1"

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#141]
https://github.com/casbin/lua-casbin/actions/runs/3900133852/jobs/6660458045

![image](https://user-images.githubusercontent.com/3787410/212009756-59e46f1a-6fd4-47d4-91da-2eb2c57dd39e.png)

**Comment by hsluoyz** [comment]
Hi @nic-chen the semantic release after merging PR: https://github.com/casbin/lua-casbin/pull/140 failed with this error. Can you please take a look and fix it?

**Comment by nic-chen** [comment]
> Hi @nic-chen the semantic release after merging PR: #140 failed with this error. Can you please take a look and fix it?

sure
