### ISSUE TITLE
docker alpine image build error while installing 'casbin'

### ISSUE THREAD

**Issue by chaitanya14** [casbin/lua-casbin#145]
I am trying to build a custom image on top of official kong image and add 'kong-authz' plugin to it, but it is erroring out at 'casbin' installation. As per the error log something to do with 'PCRE' libs. Can someone please help me in resolving this issue ? 

**Dockerfile:**

FROM docker.io/kong/kong-gateway:2.8.1.2-alpine
RUN luarocks install casbin # Erroring out line while building image.
RUN luarocks install https://raw.githubusercontent.com/casbin-lua/kong-authz/master/kong-authz-0.0.1-1.rockspec

**Error log:**

Error: Failed installing dependency: https://repo1.uhc.com/artifactory/luarocks-org-remote/lrexlib-pcre-2.9.1-1.src.rock - Could not find header file for PCRE
  No file pcre.h in /usr/local/include
  No file pcre.h in /usr/include
  No file pcre.h in /include
You may have to install PCRE in your system and/or pass PCRE_DIR or PCRE_INCDIR to the luarocks command.
Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local
Missing dependencies for casbin 1.41.2-1:
   lrexlib-pcre >= 2.9.1 (not installed)
   luaposix >= 35.0 (not installed)

casbin 1.41.2-1 depends on lua >= 5.1 (5.1-1 provided by VM)
casbin 1.41.2-1 depends on lualogging >= 1.5.1 (1.6.0-2 installed)
casbin 1.41.2-1 depends on lrexlib-pcre >= 2.9.1 (not installed)
Installing https://repo1.uhc.com/artifactory/luarocks-org-remote/lrexlib-pcre-2.9.1-1.src.rock
The command '/bin/sh -c luarocks install casbin' returned a non-zero code: 1

**Comment by hsluoyz** [comment]
Hi @conghuhu do you have time to take a look?

**Comment by conghuhu** [comment]
I'm very sorry. I'm looking for a job recently. Time is very tight

**Comment by chaitanya14** [comment]
@rushitote Thanks for looking into this. Still got an error; gcc: 'not found' add i have added 'gcc' package as well. But now  I am getting C/C++ code compilation error.  Any idea ?

**Error:**
src/common.c:4:10: fatal error: stdlib.h: No such file or directory
    4 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.

Error: Build error: Failed compiling object src/common.o

**Comment by chaitanya14** [comment]
> @rushitote Thanks for looking into this. Still got an error; gcc: 'not found' add i have added 'gcc' package as well. But now I am getting C/C++ code compilation error. Any idea ?
> 
> **Error:** src/common.c:4:10: fatal error: stdlib.h: No such file or directory 4 | #include <stdlib.h> | ^~~~~~~~~~ compilation terminated.
> 
> Error: Build error: Failed compiling object src/common.o

Never Mind. adding 'libc-dev' resolved the issue.

**Comment by chaitanya14** [comment]
So final line in docker should be as below.

RUN apk add gcc pcre pcre-dev libc-dev
