### ISSUE TITLE
Does lua Casbin support 'in' operator ?

### ISSUE THREAD

**Issue by chaitanya14** [casbin/lua-casbin#148]
I have a scenario where i need to compare array in lua table to match any of the predefined array values in matcher expression.

For instance:-
m = r.obj.roles in ('qa', 'dev)

Here is obj is a lua table and roles is an array. 

Also, Is lua-casbin production ready ?

**Comment by hsluoyz** [comment]
@rushitote

**Comment by chaitanya14** [comment]
I wish there is a documentation with all lua supported matchers. We are in process of evaluating authorization solutions and getting blocked with out much of a community reference compared to others.

**Comment by rushitote** [comment]
There isn't anything for this built-in but you can create your own function to plug into the enforcer. You can see some reference for this [here](https://github.com/casbin/lua-casbin/blob/master/src/model/FunctionMap.lua#L39) and example built-in function [here](https://github.com/casbin/lua-casbin/blob/master/src/util/BuiltInFunctions.lua#L32).

**Comment by hsluoyz** [comment]
@rushitote given in is in our docs: https://casbin.org/docs/syntax-for-models#special-grammer , I think we can add it as built-in feature

**Comment by rushitote** [comment]
@hsluoyz We already support that feature. From what I understand, the issue wants is we check if the values of an array contains any value from the list of predefined strings after the 'in' operator. We can currently check for exactly one value and not an array.

**Comment by hsluoyz** [comment]
@rushitote OK! The issue title misguided me.

@chaitanya14 you can first consider implementing a custom function by your own. We also welcome you conbributing it to our official repo as a new built-in function, like named as `anyIn`. Lua-Casbin is already production-ready and used in many scenarios like OpenResty, APISIX, Kong, etc.
