### ISSUE TITLE
Support OpenResty

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#2]
Lua is the language used by the ecosystem like Nginx, OpenResty, Kong, etc. They have a solid requirement for access control like ACL, RBAC, ABAC. Some posts are like:

- https://github.com/zmartzone/lua-resty-openidc/issues/222
- https://github.com/prabago/kong-plugin-jwt-auth-rbac

So implementing Lua-Casbin will boost the related area to enhance their permission management security.

**Comment by hsluoyz** [comment]
@divy9881 any update?

**Comment by hsluoyz** [comment]
Recommended dev env:

- IDE: IntelliJ IDEA + EmmyLua Plugin (https://plugins.jetbrains.com/plugin/9768-emmylua)
- Compiler: Lua 5.1 via Luarocks (https://github.com/luarocks/luarocks/wiki/Download)
- OS: Win10 x64

![image](https://user-images.githubusercontent.com/3787410/106360597-428ef580-6354-11eb-9ffd-30b30dddd8ff.png)

**Comment by rushitote** [comment]
@hsluoyz 
I was thinking of creating a PR which would restructure the current file structure in this repo and would make it similar to that of other implementations of Casbin (like directories of config, effect, model, persist) and add basic barebones to it too. Just wanted to ask would this be fine?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/lua-casbin/commit/3757291273be4ca6db2085f92a05a6a539746f82
