### ISSUE TITLE
Add unit tests like other Casbin projects

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#27]
Some options:

- https://luaunit.readthedocs.io/
- https://github.com/openresty/test-nginx

A full list: http://lua-users.org/wiki/UnitTesting

The chosen unit test mechanism should be easy to run in local dev machine and also GitHub checks (when someone is making a PR)

**Comment by techoner** [comment]
I think [busted](http://olivinelabs.com/busted/) would be better .

**Comment by rushitote** [comment]
@techoner Should I implement the previous tests using busted then?

**Comment by hsluoyz** [comment]
@techoner The chosen unit test mechanism should be easy to run in local dev machine and also GitHub checks (when someone is making a PR). Does it work like this?

**Comment by techoner** [comment]
@hsluoyz @rushitote   I have integrated `busted` into the Github Action.

**Comment by hsluoyz** [comment]
@techoner awesome!

**Comment by hsluoyz** [comment]
> @techoner Should I implement the previous tests using busted then?

plz go ahead.

**Comment by hsluoyz** [comment]
@rushitote can we switch our tests (https://github.com/casbin/lua-casbin/blob/master/tests/util/test_Util.lua) to busted?

**Comment by rushitote** [comment]
@hsluoyz It's already done at https://github.com/casbin/lua-casbin/blob/master/spec/util/util_spec.lua and all the busted tests till now are at https://github.com/casbin/lua-casbin/tree/master/spec.

**Comment by hsluoyz** [comment]
@rushitote OK! Then can we remove the files here: https://github.com/casbin/lua-casbin/blob/master/tests/util/test_Util.lua and then rename the spec folder to tests? Because most people including me will first search for the /tests folder for test cases.

**Comment by rushitote** [comment]
@hsluoyz Alright doing it.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/lua-casbin/pull/49
