### ISSUE TITLE
Can you write a startup guide please?

### ISSUE THREAD

**Issue by 0000sir** [casbin/lua-casbin#45]
I'm trying to include casbin-lua in my project (based on openresty), but I have no clue about how to use it.

Is this project workable and usable? I believe it is, there're 7 releases after all.

So can you provide a simple guide like https://casbin.org/docs/en/get-started did?

Appreciation for your kindness.

**Comment by hsluoyz** [comment]
@rushitote I think we can first provide a get-started guide in this repo's README. Can you do this?

/cc @techoner

**Comment by rushitote** [comment]
@hsluoyz First, the CoreEnforcer/Enforcer module (with the Enforce function and tests) needs to be implemented to make this project usable, then we can create a startup guide for this. I will try to create PR for this ASAP.

**Comment by 0000sir** [comment]
Sadly to hear that ...

**Comment by hsluoyz** [comment]
@rushitote plz work on it. Thanks!

**Comment by hsluoyz** [comment]
@rushitote any update on this?

**Comment by rushitote** [comment]
@hsluoyz Currently working on this.

**Comment by hsluoyz** [comment]
@rushitote I saw the excellent tutorial here: https://rushikeshtote.com/blog/casbin-openresty-example several days ago, but today I found I cannot access it any more:

![image](https://user-images.githubusercontent.com/3787410/123951419-5a3bda00-d9d7-11eb-8cab-76a8963e2b10.png)

So besides posting the articles (this one and future ones) on your personal blog, can you also post them to a large platform like: https://medium.com/ ? So if one day your blog site goes down, the readers can still access your article's copy elsewhere. What do you think?

**Comment by rushitote** [comment]
@hsluoyz 
Yes, you are right. I have posted this article on Medium [here](https://medium.com/@rushitote/casbin-openresty-example-94865bd29d75) and will post there too for any future ones.

**Comment by hsluoyz** [comment]
@0000sir see our OpenResty Casbin middleware: https://github.com/casbin-lua/lua-resty-casbin
