### ISSUE TITLE
Creating a .rockspec for Lua Casbin

### ISSUE THREAD

**Issue by rushitote** [casbin/lua-casbin#59]
I thought of creating an updated `.rockspec` for this module so that it can be uploaded to LuaRocks. It will make Lua Casbin's and its dependencies installation much better.

So,
1. I see two Lua Casbin modules on LuaRocks - [casbin](https://luarocks.org/modules/hsluoyz/casbin) and [lua-casbin](https://luarocks.org/modules/casbin/lua-casbin). Which one will we be using?
2. We will create only a `.rockspec` file without specifying any release tag there and without any `.rock` file. So, the advantage is LuaRocks will always install the latest release from this repo. And hence we will need to update the `.rockspec` only when we need to change the version number (say from `v1` to `v2`) or when any major file has been added. Will this be fine?

Can we do this?

**Comment by hsluoyz** [comment]
I have added my rock files: https://github.com/casbin/lua-casbin/commit/ab575f03c2cb35a463854da2178e7fe37ff9f6ac

I think we can use `casbin`, like other languages (Node)

I think we still need to have release tags. Only keeping the latest release is not following our normal pattern.

**Comment by rushitote** [comment]
@hsluoyz Sure, I have updated them at #60.
