### ISSUE TITLE
Support OpenResty better: make a middleware explicitly

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#64]
We already finished the issue: https://github.com/casbin/lua-casbin/issues/2 and a README: https://github.com/casbin/lua-casbin/blob/master/Setup-OpenResty.md

But I don't think it's enough visible. Can we make a middleware for OpenResty in a seperated repo? I don't know if there's much code to write inside the middleware, but having one will have better visibility to show our integration. Casbin has a bunch of middlewares for different langs now: https://casbin.org/docs/en/middlewares and we need a first one for Lua.

Moreover, this part (https://github.com/casbin/lua-casbin/blob/master/Setup-OpenResty.md#using-lua-casbin) is not accurate any more, as we have LuaRocks module now.

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
@hsluoyz 
Sure, I can work on creating a middleware for OpenResty. Also, I will create a PR to update the setup documentation on installing Casbin.

**Comment by rushitote** [comment]
@hsluoyz Can you please create a new repo for this?

**Comment by hsluoyz** [comment]
@rushitote created: https://github.com/casbin-lua/lua-resty-casbin

**Comment by hsluoyz** [comment]
Done here: https://github.com/casbin-lua/lua-resty-casbin
