### ISSUE TITLE
Make a Kong authorization plugin based on Casbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#65]
Kong is a very popular gateway in Lua: https://github.com/Kong/kong

They have a plugin system to support 3rd-party plugins. See some RBAC plugins:

1. https://github.com/prabago/kong-plugin-jwt-auth-rbac
2. https://github.com/danis24/kong-rbac
3. https://konghq.com/blog/authorize-api-opa-kuma

We also need to make a Casbin plugin for Kong, and finally put our repo into the official plugin list: https://docs.konghq.com/hub/

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
@hsluoyz 
I am a bit new to Kong so I will try it first and then we can start working on this.

**Comment by rushitote** [comment]
Can we create a new repo in [Casbin for Lua](https://github.com/casbin-lua/)?

**Comment by hsluoyz** [comment]
@rushitote done: https://github.com/casbin-lua/kong-authz

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin-lua/kong-authz/issues/1
