### ISSUE TITLE
Make a APISiX authorization plugin based on Casbin 

### ISSUE THREAD

**Issue by hsluoyz** [casbin/lua-casbin#86]
APISIX is a very popular gateway in Lua: https://github.com/apache/apisix

They have a plugin system to support 3rd-party plugins. See some RBAC plugins: https://github.com/apache/apisix/tree/master/docs/en/latest/plugins

We also need to make a Casbin plugin for APISIX, and finally put our repo into the official plugin list: https://github.com/apache/apisix/tree/master/docs/en/latest/plugins

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
I will read up more on this.

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin-lua/apisix-authz/issues/1
