### ISSUE TITLE
Fix the warnings in luacheck

### ISSUE THREAD

**Issue by techoner** [casbin/lua-casbin#89]
@rushitote @Edmond-J-A  I added `luacheck` to ci (https://github.com/casbin/lua-casbin/pull/88), please fix the warning in `luacheck` , see: https://github.com/casbin/lua-casbin/runs/3075157392?check_suite_focus=true#step:7:1

**Comment by Edmond-J-A** [comment]
Got it.

**Comment by rushitote** [comment]
Yes, I will fix this soon.
